/* Plugin generated by AMXX-Studio */

#include <amxmodx>
#include <amxmisc>

new const PLUGIN[] = "Drop Blocker";
new const VERSION[] = "1.0";
new const AUTHOR[] = "GeDox";


public plugin_init() {
	register_plugin(PLUGIN, VERSION, AUTHOR)
	
	register_clcmd("drop", "cmdBlock");
}

public cmdBlock(id)
	return PLUGIN_HANDLED;